export const booksArray = [
  {
    title: 'Nona the Ninth',
    author: 'Tamsyn Muir',
    genre: 'Action & Adventure Fiction',
    description: 'In many ways, Nona is like other people. She lives with her family, has a job at her local school, and loves walks on the beach and meeting new dogs. But Nona`s not like other people. Six months ago she woke up in a stranger`s body, and she`s afraid she might have to give it back. The whole city is falling to pieces. A monstrous blue sphere hangs on the horizon, ready to tear the planet apart. Blood of Eden forces have surrounded the last Cohort facility and wait for the Emperor Undying to come calling. Their leaders want Nona to be the weapon that will save them from the Nine Houses. Nona would prefer to live an ordinary life with the people she loves, with Pyrrha and Camilla and Palamedes, but she also knows that nothing lasts forever.',
    logo: 'http://localhost:5000/booksLogo/Nona the Ninth.jpg',
    rating: '',
    comments: '',
    price: '$14.99',
    dateOfIssue: '2022',
  },
  {
    title: 'Harrow the Ninth',
    author: 'Tamsyn Muir',
    genre: 'Action & Adventure Fiction',
    description: 'After rocking the cosmos with her deathly debut, Tamsyn Muir continues the story of the penumbral Ninth House in Harrow the Ninth, a mind-twisting puzzle box of mystery, murder, magic, and mayhem. Nothing is as it seems in the halls of the Emperor, and the fate of the galaxy rests on one woman`s shoulders. Harrowhark Nonagesimus, last necromancer of the Ninth House, has been drafted by her Emperor to fight an unwinnable war. Side-by-side with a detested rival, Harrow must perfect her skills and become an angel of undeath — but her health is failing, her sword makes her nauseous, and even her mind is threatening to betray her.',
    logo: 'http://localhost:5000/booksLogo/Harrow the Ninth.jpg',
    rating: '',
    comments: '',
    price: '$12.99',
    dateOfIssue: '2020',
  },
  {
    title: 'A Court of Thorns and Roses',
    author: 'Sarah J. Maas',
    genre: 'Action & Adventure Fiction',
    description: 'When nineteen-year-old huntress Feyre kills a wolf in the woods, a terrifying creature arrives to demand retribution. Dragged to a treacherous magical land she knows about only from legends, Feyre discovers that her captor is not truly a beast, but one of the lethal, immortal faeries who once ruled her world.',
    logo: 'http://localhost:5000/booksLogo/A Court of Thorns and Roses.jpg',
    rating: '',
    comments: '',
    price: '$6.65',
    dateOfIssue: '2015',
  },
  {
    title: 'A Court of Mist and Fury',
    author: 'Sarah J. Maas',
    genre: 'Action & Adventure Fiction',
    description: 'Feyre has undergone more trials than one human woman can carry in her heart. Though she`s now been granted the powers and lifespan of the High Fae, she is haunted by her time Under the Mountain and the terrible deeds she performed to save the lives of Tamlin and his people.',
    logo: 'http://localhost:5000/booksLogo/A Court of Mist and Fury.jpg',
    rating: '',
    comments: '',
    price: '$9.99',
    dateOfIssue: '2016',
  },
  {
    title: 'The Ten Thousand Doors of January',
    author: 'Alix E. Harrow',
    genre: 'Historical Fiction',
    description: 'In the early 1900s, a young woman embarks on a fantastical journey of self-discovery after finding a mysterious book in this captivating and lyrical debut. n a sprawling mansion filled with peculiar treasures, January Scaller is a curiosity herself. As the ward of the wealthy Mr. Locke, she feels little different from the artifacts that decorate the halls: carefully maintained, largely ignored, and utterly out of place.',
    logo: 'http://localhost:5000/booksLogo/The Ten Thousand Doors of January.jpg',
    rating: '',
    comments: '',
    price: '$9.99',
    dateOfIssue: '2019',
  },
  {
    title: 'A Mirror Mended',
    author: 'Alix E. Harrow',
    genre: 'Historical Fiction',
    description: 'Zinnia Gray, professional fairy-tale fixer and lapsed Sleeping Beauty is over rescuing snoring princesses. Once you’ve rescued a dozen damsels and burned fifty spindles, once you’ve gotten drunk with twenty good fairies and made out with one too many members of the royal family, you start to wish some of these girls would just get a grip and try solving their own narrative issues.',
    logo: 'http://localhost:5000/booksLogo/A Mirror Mended.jpg',
    rating: '',
    comments: '',
    price: '$9.99',
    dateOfIssue: '2019',
  },
  {
    title: 'The Hero with a Thousand Faces',
    author: 'Joseph Campbell',
    genre: 'Mythology',
    description: 'Since its release in 1949, The Hero with a Thousand Faceshas influenced millions of readers by combining the insights of modern psychology with Joseph Campbell’s revolutionary understanding of comparative mythology. In these pages, Campbell outlines the Hero’s Journey, a universal motif of adventure and transformation that runs through virtually all of the world’s mythic traditions. He also explores the Cosmogonic Cycle, the mythic pattern of world creation and destruction.',
    logo: 'http://localhost:5000/booksLogo/The Hero with a Thousand Faces.jpg',
    rating: '',
    comments: '',
    price: '$15.59',
    dateOfIssue: '2020',
  },
  {
    title: 'The Power of Myth',
    author: 'Joseph Campbell',
    genre: 'Mythology',
    description: 'The Power of Myth launched an extraordinary resurgence of interest in Joseph Campbell and his work. A preeminent scholar, writer, and teacher, he has had a profound influence on millions of people--including Star Wars creator George Lucas. To Campbell, mythology was the “song of the universe, the music of the spheres.” With Bill Moyers, one of America’s most prominent journalists, as his thoughtful and engaging interviewer, The Power of Myth touches on subjects from modern marriage to virgin births, from Jesus to John Lennon, offering a brilliant combination of intelligence and wit.',
    logo: 'http://localhost:5000/booksLogo/The Power of Myth.jpg',
    rating: '',
    comments: '',
    price: '$15.38',
    dateOfIssue: '2011',
  },
  {
    title: 'Pandora`s Jar: Women in the Greek Myths',
    author: 'Natalie Haynes',
    genre: 'Fairy Tales',
    description: 'In Pandora`s Jar, the broadcaster, writer, stand-up comedian, and passionate classicist turns the tables, putting the women of the Greek myths on an equal footing with the men. With wit, humor, and savvy, Haynes revolutionizes our understanding of epic poems, stories, and plays, resurrecting them from a woman`s perspective and tracing the origins of their mythic female characters. She looks at women such as Jocasta, Oedipus mother-turned-lover-and-wife (turned Freudian sticking point), at once the cleverest person in the story and yet often unnoticed. She considers Helen of Troy, whose marriage to Paris “caused” the Trojan war—a somewhat uneven response to her decision to leave her husband for another man. She demonstrates how the vilified Medea was like an ancient Beyonce—getting her revenge on the man who hurt and betrayed her, if by extreme measures. And she turns her eye to Medusa, the original monstered woman, whose stare turned men to stone, but who wasn`t always a monster, and had her hair turned to snakes as punishment for being raped.',
    logo: 'http://localhost:5000/booksLogo/Pandora`s Jar: Women in the Greek Myths.jpg',
    rating: '',
    comments: '',
    price: '$14.39',
    dateOfIssue: '2022',
  },
  {
    title: 'Stone Blind: A Novel',
    author: 'Natalie Haynes',
    genre: 'Fairy Tales',
    description: 'When the sea god Poseidon assaults Medusa in Athene’s temple, the goddess is enraged. Furious by the violation of her sacred space, Athene takes revenge—on the young woman. Punished for Poseidon’s actions, Medusa is forever transformed. Writhing snakes replace her hair and her gaze will turn any living creature to stone. Cursed with the power to destroy all she loves with one look, Medusa condemns herself to a life of solitude.',
    logo: 'http://localhost:5000/booksLogo/Stone Blind: A Novel.jpg',
    rating: '',
    comments: '',
    price: '$17.99',
    dateOfIssue: '2022',
  },
  {
    title: 'Meditations: Novo Classics',
    author: 'Marcus Aurelius Antoninus ',
    genre: 'Ancient & Medieval Literature',
    description: 'Meditations is a series of personal writings by Marcus Aurelius, Roman Emperor from 161 to 180 AD, recording his private notes to himself and ideas on Stoic philosophy.',
    logo: 'http://localhost:5000/booksLogo/Meditations: Novo Classics.jpg',
    rating: '',
    comments: '',
    price: '$1.19',
    dateOfIssue: '2021',
  },
  {
    title: 'Meditations: The Annotated Edition',
    author: 'Marcus Aurelius Antoninus ',
    genre: 'Ancient & Medieval Literature',
    description: 'Marcus Aurelius Antoninus (121-180 CE) was the sixteenth emperor of Rome—and by far the most powerful man in the world. Yet he was also an intensely private person, with a rich interior life and one of the wisest minds of his generation. He collected his thoughts in notebooks, gems that have come to be called his Meditations. Never intended for publication, the work has proved an inexhaustible source of wisdom and one of the most important Stoic texts of all time. In often passionate language, the entries range from one-line aphorisms to essays, from profundity to bitterness. This annotated edition offers the definitive translation of this classic and much beloved text, with copious notes from world-renowned classics expert Robin Waterfield. It illuminates one of the greatest works of popular philosophy for new readers and enriches the understanding of even the most devoted Stoic.',
    logo: 'http://localhost:5000/booksLogo/Meditations: The Annotated Edition.jpg',
    rating: '',
    comments: '',
    price: '$12.99',
    dateOfIssue: '2021',
  },
];
