export const booksArray = [
  {
    title: 'Nona the Ninth',
    author: 'Tamsyn Muir',
    genres: ['Action & Adventure Fiction', 'Fantasy', 'Horror'],
    description: 'In many ways, Nona is like other people. She lives with her family, has a job at her local school, and loves walks on the beach and meeting new dogs. But Nona`s not like other people. Six months ago she woke up in a stranger`s body, and she`s afraid she might have to give it back. The whole city is falling to pieces. A monstrous blue sphere hangs on the horizon, ready to tear the planet apart. Blood of Eden forces have surrounded the last Cohort facility and wait for the Emperor Undying to come calling. Their leaders want Nona to be the weapon that will save them from the Nine Houses. Nona would prefer to live an ordinary life with the people she loves, with Pyrrha and Camilla and Palamedes, but she also knows that nothing lasts forever.',
    logo: 'http://localhost:5000/booksLogo/Nona the Ninth.jpg',
    rating: 4.0,
    comments: '',
    price: 14.99,
    dateOfIssue: '2022',
  },
  {
    title: 'Harrow the Ninth',
    author: 'Tamsyn Muir',
    genres: ['Action & Adventure Fiction', 'Fantasy', 'Horror'],
    description: 'After rocking the cosmos with her deathly debut, Tamsyn Muir continues the story of the penumbral Ninth House in Harrow the Ninth, a mind-twisting puzzle box of mystery, murder, magic, and mayhem. Nothing is as it seems in the halls of the Emperor, and the fate of the galaxy rests on one woman`s shoulders. Harrowhark Nonagesimus, last necromancer of the Ninth House, has been drafted by her Emperor to fight an unwinnable war. Side-by-side with a detested rival, Harrow must perfect her skills and become an angel of undeath — but her health is failing, her sword makes her nauseous, and even her mind is threatening to betray her.',
    logo: 'http://localhost:5000/booksLogo/Harrow the Ninth.jpg',
    rating: 3.0,
    comments: '',
    price: 12.99,
    dateOfIssue: '2020',
  },
  {
    title: 'A Court of Thorns and Roses',
    author: 'Sarah J. Maas',
    genres: ['Action & Adventure Fiction', 'Fantasy', 'Romance'],
    description: 'When nineteen-year-old huntress Feyre kills a wolf in the woods, a terrifying creature arrives to demand retribution. Dragged to a treacherous magical land she knows about only from legends, Feyre discovers that her captor is not truly a beast, but one of the lethal, immortal faeries who once ruled her world.',
    logo: 'http://localhost:5000/booksLogo/A Court of Thorns and Roses.jpg',
    rating: 4.0,
    comments: '',
    price: 6.65,
    dateOfIssue: '2015',
  },
  {
    title: 'A Court of Mist and Fury',
    author: 'Sarah J. Maas',
    genres: ['Action & Adventure Fiction', 'Fantasy', 'Romance'],
    description: 'Feyre has undergone more trials than one human woman can carry in her heart. Though she`s now been granted the powers and lifespan of the High Fae, she is haunted by her time Under the Mountain and the terrible deeds she performed to save the lives of Tamlin and his people.',
    logo: 'http://localhost:5000/booksLogo/A Court of Mist and Fury.jpg',
    rating: 5.0,
    comments: '',
    price: 9.99,
    dateOfIssue: '2016',
  },
  {
    title: 'The Ten Thousand Doors of January',
    author: 'Alix E. Harrow',
    genres: ['Historical Fiction', 'Fantasy'],
    description: 'In a sprawling mansion filled with peculiar treasures, January Scaller is a curiosity herself. As the ward of the wealthy Mr. Locke, she feels little different from the artifacts that decorate the halls: carefully maintained, largely ignored, and utterly out of place. Then she finds a strange book. A book that carries the scent of other worlds, and tells a tale of secret doors, of love, adventure and danger. Each page turn reveals impossible truths about the world and January discovers a story increasingly entwined with her own.',
    logo: 'http://localhost:5000/booksLogo/The Ten Thousand Doors of January.jpg',
    rating: 2.5,
    comments: '',
    price: 9.99,
    dateOfIssue: '2019',
  },
  {
    title: 'A Mirror Mended',
    author: 'Alix E. Harrow',
    genres: ['Historical Fiction', 'Novella'],
    description: 'Zinnia Gray, professional fairy-tale fixer and lapsed Sleeping Beauty is over rescuing snoring princesses. Once you’ve rescued a dozen damsels and burned fifty spindles, once you’ve gotten drunk with twenty good fairies and made out with one too many members of the royal family, you start to wish some of these girls would just get a grip and try solving their own narrative issues.',
    logo: 'http://localhost:5000/booksLogo/A Mirror Mended.jpg',
    rating: 4.0,
    comments: '',
    price: 9.99,
    dateOfIssue: '2019',
  },
  {
    title: 'The Hero with a Thousand Faces',
    author: 'Joseph Campbell',
    genres: ['Mythology', 'Philosophy'],
    description: 'Since its release in 1949, The Hero with a Thousand Faceshas influenced millions of readers by combining the insights of modern psychology with Joseph Campbell’s revolutionary understanding of comparative mythology. In these pages, Campbell outlines the Hero’s Journey, a universal motif of adventure and transformation that runs through virtually all of the world’s mythic traditions. He also explores the Cosmogonic Cycle, the mythic pattern of world creation and destruction.',
    logo: 'http://localhost:5000/booksLogo/The Hero with a Thousand Faces.jpg',
    rating: 4.5,
    comments: '',
    price: 15.59,
    dateOfIssue: '2020',
  },
  {
    title: 'The Power of Myth',
    author: 'Joseph Campbell',
    genres: ['Mythology', 'Philosophy', 'Historical Fiction'],
    description: 'The Power of Myth launched an extraordinary resurgence of interest in Joseph Campbell and his work. A preeminent scholar, writer, and teacher, he has had a profound influence on millions of people--including Star Wars creator George Lucas. To Campbell, mythology was the “song of the universe, the music of the spheres.” With Bill Moyers, one of America’s most prominent journalists, as his thoughtful and engaging interviewer, The Power of Myth touches on subjects from modern marriage to virgin births, from Jesus to John Lennon, offering a brilliant combination of intelligence and wit.',
    logo: 'http://localhost:5000/booksLogo/The Power of Myth.jpg',
    rating: 3.5,
    comments: '',
    price: 15.38,
    dateOfIssue: '2011',
  },
  {
    title: 'Pandora`s Jar: Women in the Greek Myths',
    author: 'Natalie Haynes',
    genres: ['Fairy Tales', 'Fantasy'],
    description: 'In Pandora`s Jar, the broadcaster, writer, stand-up comedian, and passionate classicist turns the tables, putting the women of the Greek myths on an equal footing with the men. With wit, humor, and savvy, Haynes revolutionizes our understanding of epic poems, stories, and plays, resurrecting them from a woman`s perspective and tracing the origins of their mythic female characters. She looks at women such as Jocasta, Oedipus mother-turned-lover-and-wife (turned Freudian sticking point), at once the cleverest person in the story and yet often unnoticed. She considers Helen of Troy, whose marriage to Paris “caused” the Trojan war—a somewhat uneven response to her decision to leave her husband for another man. She demonstrates how the vilified Medea was like an ancient Beyonce—getting her revenge on the man who hurt and betrayed her, if by extreme measures. And she turns her eye to Medusa, the original monstered woman, whose stare turned men to stone, but who wasn`t always a monster, and had her hair turned to snakes as punishment for being raped.',
    logo: 'http://localhost:5000/booksLogo/Pandora`s Jar Women in the Greek Myths.jpg',
    rating: 5.0,
    comments: '',
    price: 14.39,
    dateOfIssue: '2022',
  },
  {
    title: 'Stone Blind: A Novel',
    author: 'Natalie Haynes',
    genres: ['Fairy Tales', 'Historical Fiction'],
    description: 'When the sea god Poseidon assaults Medusa in Athene’s temple, the goddess is enraged. Furious by the violation of her sacred space, Athene takes revenge—on the young woman. Punished for Poseidon’s actions, Medusa is forever transformed. Writhing snakes replace her hair and her gaze will turn any living creature to stone. Cursed with the power to destroy all she loves with one look, Medusa condemns herself to a life of solitude.',
    logo: 'http://localhost:5000/booksLogo/Stone Blind A Novel.jpg',
    rating: 5.0,
    comments: '',
    price: 17.99,
    dateOfIssue: '2022',
  },
  {
    title: 'Meditations: Novo Classics',
    author: 'Marcus Aurelius Antoninus',
    genres: ['Ancient & Medieval Literature'],
    description: 'Meditations is a series of personal writings by Marcus Aurelius, Roman Emperor from 161 to 180 AD, recording his private notes to himself and ideas on Stoic philosophy.',
    logo: 'http://localhost:5000/booksLogo/Meditations Novo Classics.jpg',
    rating: 3.5,
    comments: '',
    price: 1.19,
    dateOfIssue: '2021',
  },
  {
    title: 'Fairy Tale',
    author: 'Stephen King',
    genres: ['Horror', 'Thriller', 'Fantasy'],
    description: 'Charlie Reade looks like a regular high school kid, great at baseball and football, a decent student. But he carries a heavy load. His mom was killed in a hit-and-run accident when he was ten, and grief drove his dad to drink. Charlie learned how to take care of himself—and his dad. When Charlie is seventeen, he meets a dog named Radar and her aging master, Howard Bowditch, a recluse in a big house at the top of a big hill, with a locked shed in the backyard. Sometimes strange sounds emerge from it.',
    logo: 'http://localhost:5000/booksLogo/Fairy Tale.jpg',
    rating: 5.0,
    comments: '',
    price: 20.39,
    dateOfIssue: '2022',
  },
  {
    title: 'The Stand',
    author: 'Stephen King',
    genres: ['Horror', 'Thriller', 'Fantasy'],
    description: 'This is the way the world ends: with a nanosecond of computer error in a Defense Department laboratory and a million casual contacts that form the links in a chain letter of death. And here is the bleak new world of the day after: a world stripped of its institutions and emptied of 99 percent of its people. A world in which a handful of panicky survivors choose sides -- or are chosen. A world in which good rides on the frail shoulders of the 108-year-old Mother Abigail -- and the worst nightmares of evil are embodied in a man with a lethal smile and unspeakable powers: Randall Flagg, the dark man.',
    logo: 'http://localhost:5000/booksLogo/The Stand.jpg',
    rating: 4.0,
    comments: '',
    price: 7.93,
    dateOfIssue: '2008',
  },
  {
    title: 'Later',
    author: 'Stephen King',
    genres: ['Horror', 'Mystery', 'Thriller', 'Fantasy'],
    description: 'The son of a struggling single mother, Jamie Conklin just wants an ordinary childhood. But Jamie is no ordinary child. Born with an unnatural ability his mom urges him to keep secret, Jamie can see what no one else can see and learn what no one else can learn. But the cost of using this ability is higher than Jamie can imagine – as he discovers when an NYPD detective draws him into the pursuit of a killer who has threatened to strike from beyond the grave.',
    logo: 'http://localhost:5000/booksLogo/Later.jpg',
    rating: 3.5,
    comments: '',
    price: 9.99,
    dateOfIssue: '2021',
  },
  {
    title: 'American Psycho',
    author: 'Bret Easton Ellis',
    genres: ['Fiction Satire'],
    description: 'Patrick Bateman moves among the young and trendy in 1980s Manhattan. Young, handsome, and well educated, Bateman earns his fortune on Wall Street by day while spending his nights in ways we cannot begin to fathom. Expressing his true self through torture and murder, Bateman prefigures an apocalyptic horror that no society could bear to confront.',
    logo: 'http://localhost:5000/booksLogo/American Psycho.jpg',
    rating: 4.0,
    comments: '',
    price: 14.32,
    dateOfIssue: '2010',
  },
  {
    title: 'The Shards: A novel',
    author: 'Bret Easton Ellis',
    genres: ['Fiction Satire', 'Thriller'],
    description: 'Seventeen-year-old Bret is a senior at the exclusive Buckley prep school when a new student arrives with a mysterious past. Robert Mallory is bright, handsome, charismatic, and shielding a secret from Bret and his friends even as he becomes a part of their tightly knit circle. Bret’s obsession with Mallory is equaled only by his increasingly unsettling preoccupation with the Trawler, a serial killer on the loose who seems to be drawing ever closer to Bret and his friends, taunting them—and Bret in particular—with grotesque threats and horrific, sharply local acts of violence. The coincidences are uncanny, but they are also filtered through the imagination of a teenager whose gifts for constructing narrative from the filaments of his own life are about to make him one of the most explosive literary sensations of his generation. Can he trust his friends—or his own mind—to make sense of the danger they appear to be in? Thwarted by the world and by his own innate desires, buffeted by unhealthy fixations, he spirals into paranoia and isolation as the relationship between the Trawler and Robert Mallory hurtles inexorably toward a collision.',
    logo: 'http://localhost:5000/booksLogo/The Shards A novel.jpg',
    rating: 4.5,
    comments: '',
    price: 17.99,
    dateOfIssue: '2022',
  },
  {
    title: 'Born a Crime: Stories from a South African Childhood',
    author: 'Trevor Noah',
    genres: ['Fiction Satire', 'Biography'],
    description: 'Trevor Noah’s unlikely path from apartheid South Africa to the desk of The Daily Show began with a criminal act: his birth. Trevor was born to a white Swiss father and a black Xhosa mother at a time when such a union was punishable by five years in prison. Living proof of his parents’ indiscretion, Trevor was kept mostly indoors for the earliest years of his life, bound by the extreme and often absurd measures his mother took to hide him from a government that could, at any moment, steal him away. Finally liberated by the end of South Africa’s tyrannical white rule, Trevor and his mother set forth on a grand adventure, living openly and freely and embracing the opportunities won by a centuries-long struggle.',
    logo: 'http://localhost:5000/booksLogo/Born a Crime Stories from a South African Childhood.jpg',
    rating: 4.5,
    comments: '',
    price: 3.85,
    dateOfIssue: '2019',
  },
    {
    title: 'Gideon the Ninth',
    author: 'Tamsyn Muir',
    genres: ['Action & Adventure Fiction', 'Fantasy', 'Horror'],
    description: 'Brought up by unfriendly, ossifying nuns, ancient retainers, and countless skeletons, Gideon is ready to abandon a life of servitude and an afterlife as a reanimated corpse. She packs up her sword, her shoes, and her dirty magazines, and prepares to launch her daring escape. But her childhood nemesis won`t set her free without a service. Harrowhark Nonagesimus, Reverend Daughter of the Ninth House and bone witch extraordinaire, has been summoned into action. The Emperor has invited the heirs to each of his loyal Houses to a deadly trial of wits and skill. If Harrowhark succeeds she will become an immortal, all-powerful servant of the Resurrection, but no necromancer can ascend without their cavalier. Without Gideons sword, Harrow will fail, and the Ninth House will die.',
    logo: 'http://localhost:5000/booksLogo/Gideon the Ninth.jpg',
    rating: 4.0,
    comments: '',
    price: 19.43,
    dateOfIssue: '2019',
  },
  {
    title: 'The Locked Room',
    author: 'Elly Griffiths',
    genres: ['Mystery', 'Horror'],
    description: 'Three years after her mother`s death, Ruth is finally sorting through her things when she finds a curious relic: a decades-old photograph of her own Norfolk cottage--before she lived there--with a peculiar inscription on the back. Ruth returns to the cot-tage to uncover its meaning as Norfolk`s first cases of Covid-19 make headlines, leaving her and Kate to shelter in place there. They struggle to stave off isolation by clapping for frontline workers each evening and befriending a kind neighbor, Zoe, from a distance. Meanwhile, Nelson is investigating a series of deaths of women that may or may not be suicide. When he links a case to an archaeological dis-covery, he breaks curfew to visit Ruth and enlist her help. But the further Nelson investigates the deaths, the closer he gets to Ruth`s isolated cot-tage--until Ruth, Zoe, and Kate all go missing, and Nelson is left scrambling to find them before it`s too late.',
    logo: 'http://localhost:5000/booksLogo/The Locked Room.jpg',
    rating: 3.5,
    comments: '',
    price: 26.03,
    dateOfIssue: '2022',
  },
  {
    title: 'Descendant of the Crane',
    author: 'Joan He',
    genres: ['Fantasy', 'Mythology'],
    description: 'In New York Times and Indie bestselling author Joan He`s debut novel, Descendant of the Crane, a determined and vulnerable young heroine struggles to do right in a world brimming with deception. This gorgeous, Chinese-inspired fantasy is packed with dizzying twists, complex characters, and intricate politics. For princess Hesina of Yan, the palace is her home, but her father is her world. He taught her how to defend against the corruption and excesses of the old kings, before revolutionaries purged them and their seers and established the dynasty anew. Before he died, he was supposed to teach her how to rule.',
    logo: 'http://localhost:5000/booksLogo/Descendant of the Crane.jpeg',
    rating: 4.5,
    comments: '',
    price: 11.15,
    dateOfIssue: '2022',
  },
  {
    title: 'Strike the Zither',
    author: 'Joan He',
    genres: ['Fantasy', 'Mystery'],
    description: 'The year is 414 of the Xin Dynasty, and chaos abounds. A puppet empress is on the throne. The realm has fractured into three factions and three warlordesses hoping to claim the continent for themselves. But Zephyr knows it`s no contest. Orphaned at a young age, Zephyr took control of her fate by becoming the best strategist of the land and serving under Xin Ren, a warlordess whose loyalty to the empress is double-edged--while Ren`s honor draws Zephyr to her cause, it also jeopardizes their survival in a war where one must betray or be betrayed. When Zephyr is forced to infiltrate an enemy camp to keep Ren`s followers from being slaughtered, she encounters the enigmatic Crow, an opposing strategist who is finally her match. But there are more enemies than one--and not all of them are human.',
    logo: 'http://localhost:5000/booksLogo/Strike the Zither.jpg',
    rating: 4.5,
    comments: '',
    price: 17.65,
    dateOfIssue: '2022',
  },
  {
    title: 'The Priory of the Orange Tree',
    author: 'Samantha Shannon',
    genres: ['Fantasy', 'Fairy Tales'],
    description: 'The House of Berethnet has ruled Inys for a thousand years. Still unwed, Queen Sabran the Ninth must conceive a daughter to protect her realm from destruction--but assassins are getting closer to her door. Ead Duryan is an outsider at court. Though she has risen to the position of lady-in-waiting, she is loyal to a hidden society of mages. Ead keeps a watchful eye on Sabran, secretly protecting her with forbidden magic. Across the dark sea, Tané has trained all her life to be a dragonrider, but is forced to make a choice that could see her life unravel. Meanwhile, the divided East and West refuse to parley, and forces of chaos are rising from their sleep.',
    logo: 'http://localhost:5000/booksLogo/The Priory of the Orange Tree.jpg',
    rating: 4.0,
    comments: '',
    price: 18.16,
    dateOfIssue: '2020',
  },
  {
    title: 'The Silmarillion',
    author: 'J. R. R. Tolkien',
    genres: ['Fantasy', 'Fairy Tales'],
    description: 'The story of the creation of the world and of the First Age, this is the ancient drama to which the characters in The Lord of the Rings look back and in whose events some of them, such as Elrond and Galadriel, took part. The three Silmarils were jewels created by Fëanor, most gifted of the Elves. Within them was imprisoned the Light of the Two Trees of Valinor before the Trees themselves were destroyed by Morgoth, the first Dark Lord. Thereafter, the unsullied Light of Valinor lived on only in the Silmarils, but they were seized by Morgoth and set in his crown, which was guarded in the impenetrable fortress of Angband in the north of Middle-earth.',
    logo: 'http://localhost:5000/booksLogo/The Silmarillion.jpg',
    rating: 5.0,
    comments: '',
    price: 16.73,
    dateOfIssue: '2014',
  },
  {
    title: 'After I Do',
    author: 'Taylor Jenkins Reid',
    genres: ['Romance', 'Action & Adventure Fiction'],
    description: 'From the New York Times bestselling author of The Seven Husbands of Evelyn Hugo "A seductive twist on the timeless tale of a couple trying to rediscover love in a marriage brought low by the challenges of domestic togetherness...touching, perceptive, and achingly honest." --Beatriz Williams, New York Times bestselling authorWhen Lauren and Ryan`s marriage reaches the breaking point, they come up with an unconventional plan. They decide to take a year off in the hopes of finding a way to fall in love again. One year apart, and only one rule: they cannot contact each other. Aside from that, anything goes. Lauren embarks on a journey of self-discovery, quickly finding that her friends and family have their own ideas about the meaning of marriage. These influences, as well as her own healing process and the challenges of living apart from Ryan, begin to change Lauren`s ideas about monogamy and marriage. She starts to question: When you can have romance without loyalty and commitment without marriage, when love and lust are no longer tied together, what do you value? What are you willing to fight for? This is a love story about what happens when the love fades. It`s about staying in love, seizing love, forsaking love, and committing to love with everything you`ve got. And above all, After I Do is the story of a couple caught up in an old game--and searching for a new road to happily ever after.',
    logo: 'http://localhost:5000/booksLogo/After I Do.jpg',
    rating: 4.0,
    comments: '',
    price: 16.74,
    dateOfIssue: '2014',
  },
];
