export const booksArray = [
  {
    title: 'Nona the Ninth',
    author: 'Tamsyn Muir',
    genres: ['Action & Adventure Fiction', 'Fantasy', 'Horror'],
    description: 'In many ways, Nona is like other people. She lives with her family, has a job at her local school, and loves walks on the beach and meeting new dogs. But Nona`s not like other people. Six months ago she woke up in a stranger`s body, and she`s afraid she might have to give it back. The whole city is falling to pieces. A monstrous blue sphere hangs on the horizon, ready to tear the planet apart. Blood of Eden forces have surrounded the last Cohort facility and wait for the Emperor Undying to come calling. Their leaders want Nona to be the weapon that will save them from the Nine Houses. Nona would prefer to live an ordinary life with the people she loves, with Pyrrha and Camilla and Palamedes, but she also knows that nothing lasts forever.',
    logo: 'http://localhost:5000/booksLogo/Nona the Ninth.jpg',
    rating: 4.0,
    comments: '',
    price: 14.99,
    dateOfIssue: '2022',
  },
  {
    title: 'Harrow the Ninth',
    author: 'Tamsyn Muir',
    genres: ['Action & Adventure Fiction', 'Fantasy', 'Horror'],
    description: 'After rocking the cosmos with her deathly debut, Tamsyn Muir continues the story of the penumbral Ninth House in Harrow the Ninth, a mind-twisting puzzle box of mystery, murder, magic, and mayhem. Nothing is as it seems in the halls of the Emperor, and the fate of the galaxy rests on one woman`s shoulders. Harrowhark Nonagesimus, last necromancer of the Ninth House, has been drafted by her Emperor to fight an unwinnable war. Side-by-side with a detested rival, Harrow must perfect her skills and become an angel of undeath — but her health is failing, her sword makes her nauseous, and even her mind is threatening to betray her.',
    logo: 'http://localhost:5000/booksLogo/Harrow the Ninth.jpg',
    rating: 3.0,
    comments: '',
    price: 12.99,
    dateOfIssue: '2020',
  },
  {
    title: 'A Court of Thorns and Roses',
    author: 'Sarah J. Maas',
    genres: ['Action & Adventure Fiction', 'Fantasy', 'Romance'],
    description: 'When nineteen-year-old huntress Feyre kills a wolf in the woods, a terrifying creature arrives to demand retribution. Dragged to a treacherous magical land she knows about only from legends, Feyre discovers that her captor is not truly a beast, but one of the lethal, immortal faeries who once ruled her world.',
    logo: 'http://localhost:5000/booksLogo/A Court of Thorns and Roses.jpg',
    rating: 4.0,
    comments: '',
    price: 6.65,
    dateOfIssue: '2015',
  },
  {
    title: 'A Court of Mist and Fury',
    author: 'Sarah J. Maas',
    genres: ['Action & Adventure Fiction', 'Fantasy', 'Romance'],
    description: 'Feyre has undergone more trials than one human woman can carry in her heart. Though she`s now been granted the powers and lifespan of the High Fae, she is haunted by her time Under the Mountain and the terrible deeds she performed to save the lives of Tamlin and his people.',
    logo: 'http://localhost:5000/booksLogo/A Court of Mist and Fury.jpg',
    rating: 5.0,
    comments: '',
    price: 9.99,
    dateOfIssue: '2016',
  },
  {
    title: 'The Ten Thousand Doors of January',
    author: 'Alix E. Harrow',
    genres: ['Historical Fiction', 'Fantasy'],
    description: 'In a sprawling mansion filled with peculiar treasures, January Scaller is a curiosity herself. As the ward of the wealthy Mr. Locke, she feels little different from the artifacts that decorate the halls: carefully maintained, largely ignored, and utterly out of place. Then she finds a strange book. A book that carries the scent of other worlds, and tells a tale of secret doors, of love, adventure and danger. Each page turn reveals impossible truths about the world and January discovers a story increasingly entwined with her own.',
    logo: 'http://localhost:5000/booksLogo/The Ten Thousand Doors of January.jpg',
    rating: 2.5,
    comments: '',
    price: 9.99,
    dateOfIssue: '2019',
  },
  {
    title: 'A Mirror Mended',
    author: 'Alix E. Harrow',
    genres: ['Historical Fiction', 'Novella'],
    description: 'Zinnia Gray, professional fairy-tale fixer and lapsed Sleeping Beauty is over rescuing snoring princesses. Once you’ve rescued a dozen damsels and burned fifty spindles, once you’ve gotten drunk with twenty good fairies and made out with one too many members of the royal family, you start to wish some of these girls would just get a grip and try solving their own narrative issues.',
    logo: 'http://localhost:5000/booksLogo/A Mirror Mended.jpg',
    rating: 4.0,
    comments: '',
    price: 9.99,
    dateOfIssue: '2019',
  },
  {
    title: 'The Hero with a Thousand Faces',
    author: 'Joseph Campbell',
    genres: ['Mythology', 'Philosophy'],
    description: 'Since its release in 1949, The Hero with a Thousand Faceshas influenced millions of readers by combining the insights of modern psychology with Joseph Campbell’s revolutionary understanding of comparative mythology. In these pages, Campbell outlines the Hero’s Journey, a universal motif of adventure and transformation that runs through virtually all of the world’s mythic traditions. He also explores the Cosmogonic Cycle, the mythic pattern of world creation and destruction.',
    logo: 'http://localhost:5000/booksLogo/The Hero with a Thousand Faces.jpg',
    rating: 4.5,
    comments: '',
    price: 15.59,
    dateOfIssue: '2020',
  },
  {
    title: 'The Power of Myth',
    author: 'Joseph Campbell',
    genres: ['Mythology', 'Philosophy', 'Historical Fiction'],
    description: 'The Power of Myth launched an extraordinary resurgence of interest in Joseph Campbell and his work. A preeminent scholar, writer, and teacher, he has had a profound influence on millions of people--including Star Wars creator George Lucas. To Campbell, mythology was the “song of the universe, the music of the spheres.” With Bill Moyers, one of America’s most prominent journalists, as his thoughtful and engaging interviewer, The Power of Myth touches on subjects from modern marriage to virgin births, from Jesus to John Lennon, offering a brilliant combination of intelligence and wit.',
    logo: 'http://localhost:5000/booksLogo/The Power of Myth.jpg',
    rating: 3.5,
    comments: '',
    price: 15.38,
    dateOfIssue: '2011',
  },
  {
    title: 'Pandora`s Jar: Women in the Greek Myths',
    author: 'Natalie Haynes',
    genres: ['Fairy Tales', 'Fantasy'],
    description: 'In Pandora`s Jar, the broadcaster, writer, stand-up comedian, and passionate classicist turns the tables, putting the women of the Greek myths on an equal footing with the men. With wit, humor, and savvy, Haynes revolutionizes our understanding of epic poems, stories, and plays, resurrecting them from a woman`s perspective and tracing the origins of their mythic female characters. She looks at women such as Jocasta, Oedipus mother-turned-lover-and-wife (turned Freudian sticking point), at once the cleverest person in the story and yet often unnoticed. She considers Helen of Troy, whose marriage to Paris “caused” the Trojan war—a somewhat uneven response to her decision to leave her husband for another man. She demonstrates how the vilified Medea was like an ancient Beyonce—getting her revenge on the man who hurt and betrayed her, if by extreme measures. And she turns her eye to Medusa, the original monstered woman, whose stare turned men to stone, but who wasn`t always a monster, and had her hair turned to snakes as punishment for being raped.',
    logo: 'http://localhost:5000/booksLogo/Pandora`s Jar Women in the Greek Myths.jpg',
    rating: 5.0,
    comments: '',
    price: 14.39,
    dateOfIssue: '2022',
  },
  {
    title: 'Stone Blind: A Novel',
    author: 'Natalie Haynes',
    genres: ['Fairy Tales', 'Historical Fiction'],
    description: 'When the sea god Poseidon assaults Medusa in Athene’s temple, the goddess is enraged. Furious by the violation of her sacred space, Athene takes revenge—on the young woman. Punished for Poseidon’s actions, Medusa is forever transformed. Writhing snakes replace her hair and her gaze will turn any living creature to stone. Cursed with the power to destroy all she loves with one look, Medusa condemns herself to a life of solitude.',
    logo: 'http://localhost:5000/booksLogo/Stone Blind A Novel.jpg',
    rating: 5.0,
    comments: '',
    price: 17.99,
    dateOfIssue: '2022',
  },
  {
    title: 'Meditations: Novo Classics',
    author: 'Marcus Aurelius Antoninus',
    genres: ['Ancient & Medieval Literature'],
    description: 'Meditations is a series of personal writings by Marcus Aurelius, Roman Emperor from 161 to 180 AD, recording his private notes to himself and ideas on Stoic philosophy.',
    logo: 'http://localhost:5000/booksLogo/Meditations Novo Classics.jpg',
    rating: 3.5,
    comments: '',
    price: 1.19,
    dateOfIssue: '2021',
  },
  {
    title: 'Fairy Tale',
    author: 'Stephen King',
    genres: ['Horror', 'Thriller', 'Fantasy'],
    description: 'Charlie Reade looks like a regular high school kid, great at baseball and football, a decent student. But he carries a heavy load. His mom was killed in a hit-and-run accident when he was ten, and grief drove his dad to drink. Charlie learned how to take care of himself—and his dad. When Charlie is seventeen, he meets a dog named Radar and her aging master, Howard Bowditch, a recluse in a big house at the top of a big hill, with a locked shed in the backyard. Sometimes strange sounds emerge from it.',
    logo: 'http://localhost:5000/booksLogo/Fairy Tale.jpg',
    rating: 5.0,
    comments: '',
    price: 20.39,
    dateOfIssue: '2022',
  },
  {
    title: 'The Stand',
    author: 'Stephen King',
    genres: ['Horror', 'Thriller', 'Fantasy'],
    description: 'This is the way the world ends: with a nanosecond of computer error in a Defense Department laboratory and a million casual contacts that form the links in a chain letter of death. And here is the bleak new world of the day after: a world stripped of its institutions and emptied of 99 percent of its people. A world in which a handful of panicky survivors choose sides -- or are chosen. A world in which good rides on the frail shoulders of the 108-year-old Mother Abigail -- and the worst nightmares of evil are embodied in a man with a lethal smile and unspeakable powers: Randall Flagg, the dark man.',
    logo: 'http://localhost:5000/booksLogo/The Stand.jpg',
    rating: 4.0,
    comments: '',
    price: 7.93,
    dateOfIssue: '2008',
  },
  {
    title: 'Later',
    author: 'Stephen King',
    genres: ['Horror', 'Mystery', 'Thriller', 'Fantasy'],
    description: 'The son of a struggling single mother, Jamie Conklin just wants an ordinary childhood. But Jamie is no ordinary child. Born with an unnatural ability his mom urges him to keep secret, Jamie can see what no one else can see and learn what no one else can learn. But the cost of using this ability is higher than Jamie can imagine – as he discovers when an NYPD detective draws him into the pursuit of a killer who has threatened to strike from beyond the grave.',
    logo: 'http://localhost:5000/booksLogo/Later.jpg',
    rating: 3.5,
    comments: '',
    price: 9.99,
    dateOfIssue: '2021',
  },
  {
    title: 'American Psycho',
    author: 'Bret Easton Ellis',
    genres: ['Fiction Satire'],
    description: 'Patrick Bateman moves among the young and trendy in 1980s Manhattan. Young, handsome, and well educated, Bateman earns his fortune on Wall Street by day while spending his nights in ways we cannot begin to fathom. Expressing his true self through torture and murder, Bateman prefigures an apocalyptic horror that no society could bear to confront.',
    logo: 'http://localhost:5000/booksLogo/American Psycho.jpg',
    rating: 4.0,
    comments: '',
    price: 14.32,
    dateOfIssue: '2010',
  },
  {
    title: 'The Shards: A novel',
    author: 'Bret Easton Ellis',
    genres: ['Fiction Satire', 'Thriller'],
    description: 'Seventeen-year-old Bret is a senior at the exclusive Buckley prep school when a new student arrives with a mysterious past. Robert Mallory is bright, handsome, charismatic, and shielding a secret from Bret and his friends even as he becomes a part of their tightly knit circle. Bret’s obsession with Mallory is equaled only by his increasingly unsettling preoccupation with the Trawler, a serial killer on the loose who seems to be drawing ever closer to Bret and his friends, taunting them—and Bret in particular—with grotesque threats and horrific, sharply local acts of violence. The coincidences are uncanny, but they are also filtered through the imagination of a teenager whose gifts for constructing narrative from the filaments of his own life are about to make him one of the most explosive literary sensations of his generation. Can he trust his friends—or his own mind—to make sense of the danger they appear to be in? Thwarted by the world and by his own innate desires, buffeted by unhealthy fixations, he spirals into paranoia and isolation as the relationship between the Trawler and Robert Mallory hurtles inexorably toward a collision.',
    logo: 'http://localhost:5000/booksLogo/The Shards A novel.jpg',
    rating: 4.5,
    comments: '',
    price: 17.99,
    dateOfIssue: '2022',
  },
  {
    title: 'Born a Crime: Stories from a South African Childhood',
    author: 'Trevor Noah',
    genres: ['Fiction Satire', 'Biography'],
    description: 'Trevor Noah’s unlikely path from apartheid South Africa to the desk of The Daily Show began with a criminal act: his birth. Trevor was born to a white Swiss father and a black Xhosa mother at a time when such a union was punishable by five years in prison. Living proof of his parents’ indiscretion, Trevor was kept mostly indoors for the earliest years of his life, bound by the extreme and often absurd measures his mother took to hide him from a government that could, at any moment, steal him away. Finally liberated by the end of South Africa’s tyrannical white rule, Trevor and his mother set forth on a grand adventure, living openly and freely and embracing the opportunities won by a centuries-long struggle.',
    logo: 'http://localhost:5000/booksLogo/Born a Crime Stories from a South African Childhood.jpg',
    rating: 4.5,
    comments: '',
    price: 3.85,
    dateOfIssue: '2019',
  },
];
